name: Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: ['Fetch latest data']
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'mpt-backup-api' #Must be unique in Heroku
          heroku_email: 'iqmal3@outlook.com'

      - name: telegram notify
        uses: fjogeleit/http-request-action@v1.8.1
        with:
          url: 'https://api.telegram.org/bot${{secrets.TELE_BOT_API_KEY}}/sendMessage'
          method: 'POST'
          data: '{
            "chat_id": -1001220707105,
            "parse_mode": "MarkdownV2",
            "disable_web_page_preview": true,
            "text": "${{github.workflow}} *completed* \uD83C\uDF89 Deploy completed\\. Triggered by `${{github.event_name}}`\\. View [website](https:\/\/mpt-backup-api.herokuapp.com) or [action runs](https:\/\/github.com\/${{github.repository}}\/actions\/runs\/${{github.run_id}})\\."
            }'
